In [6]:
import sqlite3
import sqlalchemy
from sqlalchemy import Table, create_engine, MetaData, String, Integer, Column, Float

engine = create_engine('sqlite:///travel.db', echo = True)

meta = MetaData()

vol = Table("vol", meta, 
            Column('id_vol', String, primary_key=True), 
            Column('departureTime', String), 
            Column('arrivalTime', String),
            Column('duration', String),
            Column('departureAirportCode', String),
            Column('arrivalAirportCode', String),
            Column('airlinecodes', String),
            Column('departureDate', String),
            Column('arrivalDate', String), 
            extend_existing = True)

price = Table("price", meta, 
         Column('id_price', String), 
         Column('totalAmount', Float),
         Column('amountPerAdult', Float),
         Column('amountPerChild', Float),
         Column('amountPerInfant', Float),
         extend_existing = True)

events = Table("events", meta,
          Column('title', String),
          Column('day', String),
          Column('month', String),
          Column('city', String),
          extend_existing = True)

airport = Table("airport", meta,
           Column('airportCode', String, primary_key = True),
           Column('airportName', String),
           extend_existing = True)

airline = Table("airline", meta,
           Column('airlineCode', String, primary_key = True),
           Column('airlineName', String),
           extend_existing = True)

meta.create_all(engine)

2022-10-07 14:09:29,147 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-10-07 14:09:29,148 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("vol")
2022-10-07 14:09:29,149 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-07 14:09:29,152 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("price")
2022-10-07 14:09:29,153 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-07 14:09:29,155 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("events")
2022-10-07 14:09:29,155 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-07 14:09:29,157 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("events")
2022-10-07 14:09:29,158 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-07 14:09:29,160 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("airport")
2022-10-07 14:09:29,161 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-07 14:09:29,162 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("airline")
2022-10-07 14:09:29,163 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-07 14:09:29,165 INFO sqlalchemy.engine.Engine
CREATE TABLE events (
	title VARCHAR,
	day VARCHAR,
	month VARCHAR,
	city VARCHAR
)


2022-10-07 14:09:29,166 INFO sqlalchemy.engine.Engine [no key 0.00117s] ()
2022-10-07 14:09:29,173 INFO sqlalchemy.engine.Engine COMMIT

In [20]:
from DB_Mongo import DB_Mongo

db = DB_Mongo()

cursor = db.vol.find()

for item in cursor:
   
    
    id_vol = item.get('id')
    departureTime = item.get('departureTime')
    arrivalTime = item.get('arrivalTime')
    duration = item.get('duration')
    departureAirportCode = item.get('departureAirportCode')
    arrivalAirportCode = item.get('arrivalAirportCode')
    airlineCodes = item.get('airlineCodes')
    departureDate = item.get('departureDate')
    arrivalDate = item.get('arrivalDate')
    
    
with engine.connect() as connection:
    with connection.begin() as transaction:
        try:
            markers = ','.join('?' * 9)
            ins = 'INSERT OR REPLACE INTO {tablename} VALUES ({markers})'
            
            ins = ins.format(tablename = vol.name, markers = markers)
            
            values = []
            for id_vol_it,departureTime_it,arrivalTime_it,duration_it,departureAirportCode_it,arrivalAirportCode_it,airlineCodes_it, departureDate_it, arrivalDate_it in zip(id_vol,departureTime,arrivalTime,duration,departureAirportCode,arrivalAirportCode,airlineCodes,departureDate, arrivalDate) :
                airlineCodes_it =  ', '.join(airlineCodes_it)
                connection.execute(ins, (id_vol_it,departureTime_it,arrivalTime_it,duration_it,departureAirportCode_it,arrivalAirportCode_it,airlineCodes_it, departureDate_it, arrivalDate_it))
            
        except:
            transaction.rollback()
            raise
        else:
            transaction.commit()

2022-10-07 14:40:33,572 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-10-07 14:40:33,573 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,574 INFO sqlalchemy.engine.Engine [raw sql] ('AY4015~11-AY4174~11', '15:35:00', '23:58:00', '16h 23m', 'LHR', 'LAX', 'AY', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,578 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,579 INFO sqlalchemy.engine.Engine [raw sql] ('IB4855~11-IB4354~11', '09:05:00', '15:38:00', '14h 33m', 'LHR', 'LAX', 'IB', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,580 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,581 INFO sqlalchemy.engine.Engine [raw sql] ('SK1508~11-SK931~12', '20:30:00', '15:05:00', '26h 35m', 'LHR', 'LAX', 'SK', '2022-11-11', '2022-11-12')
2022-10-07 14:40:33,581 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,582 INFO sqlalchemy.engine.Engine [raw sql] ('AY1332~11-AY1~11', '10:20:00', '17:05:00', '14h 45m', 'LHR', 'LAX', 'AY', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,582 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,583 INFO sqlalchemy.engine.Engine [raw sql] ('IB4238~11', '13:50:00', '17:14:00', '11h 24m', 'LHR', 'LAX', 'IB', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,585 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,586 INFO sqlalchemy.engine.Engine [raw sql] ('AY5469~11', '12:30:00', '15:55:00', '11h 25m', 'LHR', 'LAX', 'AY', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,587 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,588 INFO sqlalchemy.engine.Engine [raw sql] ('KL6006~11-KL5044~11', '16:00:00', '00:58:00', '16h 58m', 'LHR', 'LAX', 'KL', '2022-11-11', '2022-11-12')
2022-10-07 14:40:33,589 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,589 INFO sqlalchemy.engine.Engine [raw sql] ('UA935~11', '15:20:00', '18:35:00', '11h 15m', 'LHR', 'LAX', 'UA', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,590 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,591 INFO sqlalchemy.engine.Engine [raw sql] ('LH2471~11-LH452~11', '08:45:00', '15:25:00', '14h 40m', 'LHR', 'LAX', 'LH', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,593 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,594 INFO sqlalchemy.engine.Engine [raw sql] ('OS7807~11-OS7867~12', '16:20:00', '20:01:00', '35h 41m', 'LHR', 'LAX', 'OS', '2022-11-11', '2022-11-12')
2022-10-07 14:40:33,595 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,596 INFO sqlalchemy.engine.Engine [raw sql] ('TK1984~11-TK179~12', '22:35:00', '11:20:00', '20h 45m', 'LHR', 'LAX', 'TK', '2022-11-11', '2022-11-12')
2022-10-07 14:40:33,597 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,598 INFO sqlalchemy.engine.Engine [raw sql] ('AY5785~11', '13:50:00', '17:14:00', '11h 24m', 'LHR', 'LAX', 'AY', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,600 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,601 INFO sqlalchemy.engine.Engine [raw sql] ('AF9301~11-AF8589~11', '09:40:00', '19:29:00', '17h 49m', 'LHR', 'LAX', 'AF', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,602 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,603 INFO sqlalchemy.engine.Engine [raw sql] ('SK500~11-SK931~11', '06:40:00', '15:05:00', '16h 25m', 'LHR', 'LAX', 'SK', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,604 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,605 INFO sqlalchemy.engine.Engine [raw sql] ('AF1581~11-AF78~11', '11:30:00', '21:00:00', '17h 30m', 'LHR', 'LAX', 'AF', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,607 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,608 INFO sqlalchemy.engine.Engine [raw sql] ('LH9260~11-LH7476~11', '12:05:00', '20:01:00', '15h 56m', 'LHR', 'LAX', 'LH', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,609 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,610 INFO sqlalchemy.engine.Engine [raw sql] ('OS7853~11-OS7705~12', '15:10:00', '20:44:00', '37h 34m', 'LHR', 'LAX', 'OS', '2022-11-11', '2022-11-12')
2022-10-07 14:40:33,611 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,612 INFO sqlalchemy.engine.Engine [raw sql] ('VS23~11', '16:55:00', '20:10:00', '11h 15m', 'LHR', 'LAX', 'VS', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,614 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,616 INFO sqlalchemy.engine.Engine [raw sql] ('UA4~11-UA1813~11', '13:45:00', '23:38:00', '17h 53m', 'LHR', 'LAX', 'UA', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,617 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,618 INFO sqlalchemy.engine.Engine [raw sql] ('IB7447~11-IB4884~12', '14:15:00', '11:43:00', '29h 28m', 'LHR', 'LAX', 'IB', '2022-11-11', '2022-11-12')
2022-10-07 14:40:33,618 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,620 INFO sqlalchemy.engine.Engine [raw sql] ('KL6082~11-KL5036~11', '09:40:00', '17:53:00', '16h 13m', 'LHR', 'LAX', 'KL', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,622 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,623 INFO sqlalchemy.engine.Engine [raw sql] ('IB7458~11-IB6171~11', '06:05:00', '16:20:00', '18h 15m', 'LHR', 'LAX', 'IB', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,624 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,625 INFO sqlalchemy.engine.Engine [raw sql] ('DL5979~11', '12:20:00', '15:35:00', '11h 15m', 'LHR', 'LAX', 'DL', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,627 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,629 INFO sqlalchemy.engine.Engine [raw sql] ('AF3666~11-AF2624~11', '10:10:00', '19:00:00', '16h 50m', 'LHR', 'LAX', 'AF', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,630 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,631 INFO sqlalchemy.engine.Engine [raw sql] ('AY5753~11-AY4022~11', '09:55:00', '17:19:00', '15h 24m', 'LHR', 'LAX', 'AY', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,632 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,633 INFO sqlalchemy.engine.Engine [raw sql] ('AY4014~11', '11:15:00', '14:39:00', '11h 24m', 'LHR', 'LAX', 'AY', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,634 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,635 INFO sqlalchemy.engine.Engine [raw sql] ('BA1502~11', '13:50:00', '17:14:00', '11h 24m', 'LHR', 'LAX', 'BA', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,637 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,638 INFO sqlalchemy.engine.Engine [raw sql] ('AY4179~11-AY4034~11', '09:05:00', '15:38:00', '14h 33m', 'LHR', 'LAX', 'AY', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,639 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,639 INFO sqlalchemy.engine.Engine [raw sql] ('IB4265~11', '11:15:00', '14:39:00', '11h 24m', 'LHR', 'LAX', 'IB', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,641 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,642 INFO sqlalchemy.engine.Engine [raw sql] ('QR12~11-QR739~12', '18:55:00', '13:10:00', '26h 15m', 'LHR', 'LAX', 'QR', '2022-11-11', '2022-11-12')
2022-10-07 14:40:33,643 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,644 INFO sqlalchemy.engine.Engine [raw sql] ('KL6111~11-KL5302~11', '12:25:00', '20:52:00', '16h 27m', 'LHR', 'LAX', 'KL', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,645 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,646 INFO sqlalchemy.engine.Engine [raw sql] ('AF1381~11-AF78~11', '06:20:00', '21:00:00', '22h 40m', 'LHR', 'LAX', 'AF', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,647 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,648 INFO sqlalchemy.engine.Engine [raw sql] ('KL6082~11-KL7076~11', '09:40:00', '19:29:00', '17h 49m', 'LHR', 'LAX', 'KL', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,649 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,650 INFO sqlalchemy.engine.Engine [raw sql] ('EI159~11-EI69~11', '12:15:00', '18:40:00', '14h 25m', 'LHR', 'LAX', 'EI', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,651 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,652 INFO sqlalchemy.engine.Engine [raw sql] ('AY1332~11-AA8975~11', '10:20:00', '17:05:00', '14h 45m', 'LHR', 'LAX', 'AA, AY', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,653 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,655 INFO sqlalchemy.engine.Engine [raw sql] ('KL1008~11-KL603~11', '10:00:00', '15:20:00', '13h 20m', 'LHR', 'LAX', 'KL', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,656 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,656 INFO sqlalchemy.engine.Engine [raw sql] ('LH921~11-LH456~11', '06:30:00', '13:05:00', '14h 35m', 'LHR', 'LAX', 'LH', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,657 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,658 INFO sqlalchemy.engine.Engine [raw sql] ('AF1181~11-AF66~12', '19:45:00', '13:00:00', '25h 15m', 'LHR', 'LAX', 'AF', '2022-11-11', '2022-11-12')
2022-10-07 14:40:33,659 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,660 INFO sqlalchemy.engine.Engine [raw sql] ('OS7805~11-OS7867~11', '12:05:00', '20:01:00', '15h 56m', 'LHR', 'LAX', 'OS', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,665 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,666 INFO sqlalchemy.engine.Engine [raw sql] ('LX359~11-LX2807~11', '07:00:00', '16:20:00', '17h 20m', 'LHR', 'LAX', 'LX', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,667 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,669 INFO sqlalchemy.engine.Engine [raw sql] ('TK1972~11-TK179~12', '17:40:00', '11:20:00', '25h 40m', 'LHR', 'LAX', 'TK', '2022-11-11', '2022-11-12')
2022-10-07 14:40:33,670 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,671 INFO sqlalchemy.engine.Engine [raw sql] ('OS7847~11', '15:20:00', '18:35:00', '11h 15m', 'LHR', 'LAX', 'OS', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,672 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,673 INFO sqlalchemy.engine.Engine [raw sql] ('AF1381~11-AF72~11', '06:20:00', '16:05:00', '17h 45m', 'LHR', 'LAX', 'AF', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,675 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,677 INFO sqlalchemy.engine.Engine [raw sql] ('KL1000~11-KL601~11', '06:30:00', '11:50:00', '13h 20m', 'LHR', 'LAX', 'KL', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,678 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,679 INFO sqlalchemy.engine.Engine [raw sql] ('DL5977~11', '16:55:00', '20:10:00', '11h 15m', 'LHR', 'LAX', 'DL', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,679 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,680 INFO sqlalchemy.engine.Engine [raw sql] ('UA4~11-UA1599~11', '13:45:00', '21:55:00', '16h 10m', 'LHR', 'LAX', 'UA', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,681 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,681 INFO sqlalchemy.engine.Engine [raw sql] ('AA9002~11-AA8975~11', '07:30:00', '17:05:00', '17h 35m', 'LHR', 'LAX', 'AA', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,684 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,685 INFO sqlalchemy.engine.Engine [raw sql] ('BA1609~11', '11:15:00', '14:39:00', '11h 24m', 'LHR', 'LAX', 'BA', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,686 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,687 INFO sqlalchemy.engine.Engine [raw sql] ('LH9378~11-LH7498~11', '09:20:00', '17:43:00', '16h 23m', 'LHR', 'LAX', 'LH', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,688 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,690 INFO sqlalchemy.engine.Engine [raw sql] ('IB7429~11', '15:15:00', '18:35:00', '11h 20m', 'LHR', 'LAX', 'IB', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,691 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,692 INFO sqlalchemy.engine.Engine [raw sql] ('AY1340~11-AY1~11', '07:30:00', '17:05:00', '17h 35m', 'LHR', 'LAX', 'AY', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,693 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,694 INFO sqlalchemy.engine.Engine [raw sql] ('AF3624~11-AF3486~11', '12:30:00', '00:37:00', '20h 07m', 'LHR', 'LAX', 'AF', '2022-11-11', '2022-11-12')
2022-10-07 14:40:33,696 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,697 INFO sqlalchemy.engine.Engine [raw sql] ('QR16~11-QR741~13', '21:20:00', '06:45:00', '41h 25m', 'LHR', 'LAX', 'QR', '2022-11-11', '2022-11-13')
2022-10-07 14:40:33,699 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,699 INFO sqlalchemy.engine.Engine [raw sql] ('AY5473~11-AY4174~11', '11:25:00', '23:58:00', '20h 33m', 'LHR', 'LAX', 'AY', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,700 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,701 INFO sqlalchemy.engine.Engine [raw sql] ('KL1002~11-KL603~11', '08:40:00', '15:20:00', '14h 40m', 'LHR', 'LAX', 'KL', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,702 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,703 INFO sqlalchemy.engine.Engine [raw sql] ('AA137~11', '11:15:00', '14:39:00', '11h 24m', 'LHR', 'LAX', 'AA', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,704 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,705 INFO sqlalchemy.engine.Engine [raw sql] ('AF3587~11-AF3486~11', '14:30:00', '00:37:00', '18h 07m', 'LHR', 'LAX', 'AF', '2022-11-11', '2022-11-12')
2022-10-07 14:40:33,706 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,707 INFO sqlalchemy.engine.Engine [raw sql] ('AY5459~11', '15:15:00', '18:35:00', '11h 20m', 'LHR', 'LAX', 'AY', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,708 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,709 INFO sqlalchemy.engine.Engine [raw sql] ('AY5515~11-AY4174~11', '14:00:00', '23:58:00', '17h 58m', 'LHR', 'LAX', 'AY', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,710 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,712 INFO sqlalchemy.engine.Engine [raw sql] ('AZ209~11-AZ620~12', '20:00:00', '13:25:00', '25h 25m', 'LHR', 'LAX', 'AZ', '2022-11-11', '2022-11-12')
2022-10-07 14:40:33,713 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,713 INFO sqlalchemy.engine.Engine [raw sql] ('VS6712~11-VS6762~12', '19:45:00', '13:00:00', '25h 15m', 'LHR', 'LAX', 'VS', '2022-11-11', '2022-11-12')
2022-10-07 14:40:33,714 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,715 INFO sqlalchemy.engine.Engine [raw sql] ('AF1381~11-AF66~11', '06:20:00', '13:00:00', '14h 40m', 'LHR', 'LAX', 'AF', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,720 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,721 INFO sqlalchemy.engine.Engine [raw sql] ('OS7849~11-OS7705~11', '10:25:00', '18:12:00', '15h 47m', 'LHR', 'LAX', 'OS', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,722 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,725 INFO sqlalchemy.engine.Engine [raw sql] ('IB3179~11-IB6171~12', '19:40:00', '16:20:00', '28h 40m', 'LHR', 'LAX', 'IB', '2022-11-11', '2022-11-12')
2022-10-07 14:40:33,727 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,728 INFO sqlalchemy.engine.Engine [raw sql] ('AY5485~11-AY4174~11', '10:45:00', '23:58:00', '21h 13m', 'LHR', 'LAX', 'AY', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,729 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,731 INFO sqlalchemy.engine.Engine [raw sql] ('BA281~11', '12:30:00', '15:55:00', '11h 25m', 'LHR', 'LAX', 'BA', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,733 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,735 INFO sqlalchemy.engine.Engine [raw sql] ('LO286~11-LO21~11', '06:30:00', '14:25:00', '15h 55m', 'LHR', 'LAX', 'LO', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,736 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,737 INFO sqlalchemy.engine.Engine [raw sql] ('AV121~11-AV382~12', '21:40:00', '22:20:00', '32h 40m', 'LHR', 'LAX', 'AV', '2022-11-11', '2022-11-12')
2022-10-07 14:40:33,739 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,740 INFO sqlalchemy.engine.Engine [raw sql] ('LX317~11-LX40~11', '08:40:00', '16:20:00', '15h 40m', 'LHR', 'LAX', 'LX', '2022-11-11', '2022-11-11')
2022-10-07 14:40:33,741 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,742 INFO sqlalchemy.engine.Engine [raw sql] ('WS19~11-WS1514~12', '14:50:00', '16:40:00', '33h 50m', 'LHR', 'LAX', 'WS', '2022-11-11', '2022-11-12')
2022-10-07 14:40:33,742 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,743 INFO sqlalchemy.engine.Engine [raw sql] ('AV121~11-AV84~12', '21:40:00', '18:05:00', '28h 25m', 'LHR', 'LAX', 'AV', '2022-11-11', '2022-11-12')
2022-10-07 14:40:33,744 INFO sqlalchemy.engine.Engine INSERT OR REPLACE INTO vol VALUES (?,?,?,?,?,?,?,?,?)
2022-10-07 14:40:33,746 INFO sqlalchemy.engine.Engine [raw sql] ('IB7378~11-IB4151~12', '18:00:00', '20:20:00', '34h 20m', 'LHR', 'LAX', 'IB', '2022-11-11', '2022-11-12')

In [22]:
with engine.connect() as connection:
    results = connection.execute("SELECT * FROM vol LIMIT 1")
    print(results.fetchall())

2022-10-07 14:41:27,020 INFO sqlalchemy.engine.Engine SELECT * FROM vol LIMIT 1
2022-10-07 14:41:27,021 INFO sqlalchemy.engine.Engine [raw sql] ()
[('AY4015~11-AY4174~11', '15:35:00', '23:58:00', '16h 23m', 'LHR', 'LAX', 'AY', '2022-11-11', '2022-11-11')]